# SPDX-FileCopyrightText: 2026 goatest contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

version: "2"

linters:
  default: standard
  enable:
    - copyloopvar
    - mnd
    - misspell
    - nolintlint
    - thelper
    - tparallel
    - unconvert
    - whitespace
  settings:
    thelper:
      test:
        first: true
        name: false
        begin: true
      benchmark:
        first: true
        name: false
        begin: true
      tb:
        first: true
        name: false
        begin: true
      fuzz:
        first: true
        name: false
        begin: true
