# SPDX-FileCopyrightText: 2026 goatest contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

version = 1
SPDX-PackageName = "goatest"
SPDX-PackageSupplier = "goatest contributors <noreply@goatest.invalid>"
SPDX-PackageDownloadLocation = "https://github.com/P4suta/go-mutants"


[[annotations]]
path = ["go.mod", "go.sum"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 goatest contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [".gitignore"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 goatest contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = [
  "internal/trace/schema.json",
  "internal/devtools/proofaudit/testdata/**",
  "internal/devtools/reportdiff/testdata/**",
  "internal/devtools/tracesummary/testdata/**",
  "internal/testkit/testdata/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 goatest contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"

[[annotations]]
path = ["LICENSE-APACHE", "LICENSE-MIT"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 goatest contributors"
SPDX-License-Identifier = "MIT OR Apache-2.0"
