---
# SPDX-FileCopyrightText: 2026 go-mutants contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:17"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:37"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    groups:
      go-dependencies:
        patterns:
          - "*"
