# SPDX-FileCopyrightText: 2026 go-mutants contributors
# SPDX-License-Identifier: MIT OR Apache-2.0

subject_length = 100
subject_capitalized = false
line_length = 220
style = "none"
merge_commit = true
